In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

cars_analysis=pd.read_csv('car_price_performance.csv')
cars_analysis

        Brand  Price  Horsepower  Fuel Efficiency
0     Brand C  91942         382             15.3
1     Brand A  70075         197             32.6
2     Brand C  84524         188             34.9
3     Brand E  68939         258             15.1
4     Brand X  66505         277             13.0
...       ...    ...         ...              ...
1995  Brand Z  34535         196             15.2
1996  Brand C  35215         377             25.3
1997  Brand E  72980         294             21.8
1998  Brand Z  55921         443             11.0
1999  Brand B  95051         225             12.4

[2000 rows x 4 columns]

In [3]:
cars_analysis.head()

     Brand  Price  Horsepower  Fuel Efficiency
0  Brand C  91942         382             15.3
1  Brand A  70075         197             32.6
2  Brand C  84524         188             34.9
3  Brand E  68939         258             15.1
4  Brand X  66505         277             13.0

In [4]:
cars_analysis.isna().sum()

Brand              0
Price              0
Horsepower         0
Fuel Efficiency    0
dtype: int64

In [5]:
cars_analysis.describe()

              Price   Horsepower  Fuel Efficiency
count   2000.000000  2000.000000      2000.000000
mean   64495.504000   302.851000        22.365650
std    20350.139304   113.890159         7.112203
min    30001.000000   100.000000        10.000000
25%    46849.750000   205.000000        16.200000
50%    64804.000000   302.000000        22.150000
75%    81987.250000   399.000000        28.525000
max    99979.000000   500.000000        35.000000

In [7]:
cars_analysis['Brand'].unique()

array(['Brand C', 'Brand A', 'Brand E', 'Brand X', 'Brand W', 'Brand Y',
       'Brand D', 'Brand B', 'Brand Z'], dtype=object)

In [10]:
brand_avg_price = cars_analysis.groupby('Brand')['Price'].mean()
brand_avg_price

Brand
Brand A    64224.495370
Brand B    64686.641350
Brand C    64707.967890
Brand D    65498.701681
Brand E    63712.542601
Brand W    63034.557018
Brand X    65405.884259
Brand Y    63880.171569
Brand Z    65244.331818
Name: Price, dtype: float64

In [12]:
brand_encoding = brand_avg_price.rank(method='dense', ascending=False).astype(int)
brand_encoding

Brand
Brand A    6
Brand B    5
Brand C    4
Brand D    1
Brand E    8
Brand W    9
Brand X    2
Brand Y    7
Brand Z    3
Name: Price, dtype: int64

In [14]:
brand_encoding_dict = brand_encoding.to_dict()
brand_encoding_dict

{'Brand A': 6,
 'Brand B': 5,
 'Brand C': 4,
 'Brand D': 1,
 'Brand E': 8,
 'Brand W': 9,
 'Brand X': 2,
 'Brand Y': 7,
 'Brand Z': 3}

In [16]:
cars_analysis['Brand_Encoded'] = cars_analysis['Brand'].map(brand_encoding_dict)

In [17]:
print(cars_analysis.head(10))

     Brand  Price  Horsepower  Fuel Efficiency  Brand_Encoded
0  Brand C  91942         382             15.3              4
1  Brand A  70075         197             32.6              6
2  Brand C  84524         188             34.9              4
3  Brand E  68939         258             15.1              8
4  Brand X  66505         277             13.0              2
5  Brand W  92762         125             18.5              9
6  Brand Y  99356         284             20.6              7
7  Brand A  38486         445             22.0              6
8  Brand A  54628         426             13.5              6
9  Brand D  93925         250             22.1              1

In [19]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [20]:
columns_to_scale = ['Horsepower', 'Fuel Efficiency']

In [22]:
cars_analysis[columns_to_scale] = scaler.fit_transform(cars_analysis[columns_to_scale])

In [23]:
print(cars_analysis.head())

     Brand  Price  Horsepower  Fuel Efficiency  Brand_Encoded
0  Brand C  91942      0.7050            0.212              4
1  Brand A  70075      0.2425            0.904              6
2  Brand C  84524      0.2200            0.996              4
3  Brand E  68939      0.3950            0.204              8
4  Brand X  66505      0.4425            0.120              2